

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author islam
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    static int sid;
    Connection connection;
    public NewJFrame3(int sidt) throws ClassNotFoundException, SQLException {
        sid = sidt;
        initComponents();
               Class.forName("oracle.jdbc.driver.OracleDriver");
        connection = null;
        connection = DriverManager.getConnection(
					"jdbc:oracle:thin:@localhost:1521:XE", "islam",
				
                "05091995");
      
    
        sid = sidt;
        int row=0;
        int col = 0;
        Statement stmt = null;
        String query = "select fname, mname, lname, ssn, address, age, gender, nationality,  mobile, email, salary, position from employee where sid=" + sid;
        stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery(query);
        while(rs.next())
        {
           col = 0;
            jTable1.setValueAt(rs.getString("fname"), row, col);
            col++;
            jTable1.setValueAt(rs.getString("mname"), row, col);
            col++;
            jTable1.setValueAt(rs.getString("lname"), row, col);
            col++;
            jTable1.setValueAt(rs.getInt("ssn") + "", row, col);
            col++;
            jTable1.setValueAt(rs.getString("address"), row, col);
            col++;
            jTable1.setValueAt(rs.getInt("age") + "", row, col);
            col++;
            jTable1.setValueAt(rs.getString("gender"), row, col);
            col++;
            jTable1.setValueAt(rs.getString("nationality"), row, col);
            col++;
            jTable1.setValueAt(rs.getInt("mobile") + "", row, col);
            col++;
            jTable1.setValueAt(rs.getString("email"), row, col);
            col++;
            jTable1.setValueAt(rs.getString("position"), row, col);
            col++;
            jTable1.setValueAt(rs.getInt("salary") + "", row, col);
            col++;
            row++;
           
        }
        String m = "u";
       System.out.println(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Middle Name", "Last Name", "SSN", "Address", "age", "Gender", "Nationality", "Mobile", "Email", "Position", "Salary"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("First Name");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Middle Name");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Last Name");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("SSN");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Address");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("age");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Gender");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("Nationality");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("Mobile");
            jTable1.getColumnModel().getColumn(9).setHeaderValue("Email");
            jTable1.getColumnModel().getColumn(10).setHeaderValue("Position");
            jTable1.getColumnModel().getColumn(11).setHeaderValue("Salary");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame3(sid).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
